### ISSUE TITLE
Issue with !star command

### ISSUE THREAD

**Issue by Note2Self** [TrustyJAID/Trusty-cogs#16]
Hi there seems to be an issue with the command !star which should allow you to manually add a message to the starboard. However, I'm getting the error 

`Name Error: name 'user' is not defined`

**Comment by TrustyJAID** [comment]
This was fixed 6 days ago. Update your version of the cog.

**Comment by Note2Self** [comment]
I've downloaded the recent version from this repo the issue still persists.

**Comment by TrustyJAID** [comment]
You'll need to post the full error message for me to figure out what is going wrong.

**Comment by Note2Self** [comment]
Fix was made thank you
